# Generated by Django 3.2 on 2021-05-26 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210526_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateAdded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
