# Generated by Django 3.2 on 2021-05-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_dateadded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='CellNumber',
            new_name='Cell_Number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='IDNumber',
            new_name='ID_Number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='IDType',
            new_name='ID_Type',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
