# Generated by Django 3.2 on 2021-10-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0011_auto_20210929_2256'),
        ('clients', '0005_client_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('Date', models.DateField()),
                ('PaymentMethod', models.CharField(choices=[('Bank Payment', 'Bank Payment'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card')], max_length=20, null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyLedger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policyledger')),
                ('Receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.receipt')),
            ],
        ),
    ]
