# Generated by Django 3.2 on 2021-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
