# Generated by Django 3.2 on 2021-08-16 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20210526_0120'),
        ('clients', '0005_client_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=10)),
                ('InceptionDate', models.DateTimeField()),
                ('CollectionDay', models.IntegerField()),
                ('DateAdded', models.DateTimeField(default=datetime.datetime.now)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.client')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EndorsementType', models.CharField(choices=[('I', 'Internal'), ('E', 'Endorsement')], max_length=20)),
                ('EndorsementReason', models.CharField(max_length=255)),
                ('EffectiveDateFrom', models.DateTimeField()),
                ('EffectiveDateTo', models.DateTimeField()),
                ('Description', models.CharField(max_length=255)),
                ('Cover', models.FloatField(null=True)),
                ('DateAdded', models.DateTimeField(default=datetime.datetime.now)),
                ('Policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberType', models.CharField(max_length=10)),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True)),
                ('DateOfBirth', models.DateField(default=datetime.datetime.now)),
                ('ID_Type', models.CharField(choices=[('ID', 'ID'), ('Passport', 'Passport')], max_length=10, null=True)),
                ('ID_Number', models.CharField(max_length=20, null=True)),
                ('Title', models.CharField(max_length=10, null=True)),
                ('Student', models.BooleanField(null=True)),
                ('DateAdded', models.DateTimeField(default=datetime.datetime.now)),
                ('PolicyVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policyversion')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(null=True)),
                ('TransactionDate', models.DateField()),
                ('CollectionDate', models.DateField()),
                ('PolicyVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policyversion')),
            ],
        ),
    ]
