# Generated by Django 3.2 on 2021-08-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='InceptionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='policymembers',
            name='MemberType',
            field=models.CharField(choices=[('Maim Member', 'Maim Member'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Adult Dependent', 'Adult Dependent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='EffectiveDateFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='EffectiveDateTo',
            field=models.DateField(),
        ),
    ]
