# Generated by Django 3.2 on 2021-08-31 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20210825_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='IsLatest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='DateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='policymembers',
            name='DateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='policymembers',
            name='DateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='DateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='EndorsementType',
            field=models.CharField(choices=[('I', 'Inception'), ('IE', 'Internal'), ('EE', 'Endorsement')], max_length=20),
        ),
    ]
