# Generated by Django 3.2 on 2021-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20210831_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='Status',
            field=models.CharField(choices=[('Un-finalised', 'Un-finalised'), ('Finalised', 'Finalised')], default='Un-finalised', max_length=20),
        ),
    ]
