# Generated by Django 3.2 on 2021-09-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_policyversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='Version_Number',
            field=models.IntegerField(default=1),
        ),
    ]
