# Generated by Django 3.2 on 2021-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_policyversion_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymembers',
            name='Premium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='EndorsementType',
            field=models.CharField(choices=[('Inception', 'Inception'), ('Internal', 'Internal'), ('Endorsement', 'Endorsement')], max_length=20),
        ),
    ]
