# Generated by Django 3.2 on 2021-09-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210526_0120'),
        ('policy', '0006_auto_20210909_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='ProductRateId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productrates'),
        ),
    ]
