# Generated by Django 3.2 on 2021-09-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_policyversion_productrateid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyversion',
            old_name='ProductRateId',
            new_name='ProductRate',
        ),
    ]
