# Generated by Django 3.2 on 2021-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_rename_productrateid_policyversion_productrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyversion',
            name='ProductRate',
        ),
        migrations.AddField(
            model_name='policymembers',
            name='Cover',
            field=models.CharField(choices=[('Option 1: R 5,000', 'Option 1: R 5,000'), ('Option 2: R 10,000', 'Option 2: R 10,000'), ('Price Per R 1,000', 'Price Per R 1,000')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policyledger',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='policymembers',
            name='Premium',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='Cover',
            field=models.CharField(choices=[('Option 1: R 5,000', 'Option 1: R 5,000'), ('Option 2: R 10,000', 'Option 2: R 10,000'), ('Price Per R 1,000', 'Price Per R 1,000')], max_length=50, null=True),
        ),
    ]
