# Generated by Django 3.2 on 2021-09-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_auto_20210916_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymembers',
            name='CoverAmount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='CoverAmount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='Cover',
            field=models.CharField(choices=[('6 Members', '6 Members'), ('8 Members', '8 Members'), ('10 Members', '10 Members'), ('Option 1: R 5,000', 'Option 1: R 5,000'), ('Option 2: R 10,000', 'Option 2: R 10,000'), ('Price Per R 1,000', 'Price Per R 1,000')], max_length=50, null=True),
        ),
    ]
