# Generated by Django 3.2 on 2021-09-29 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0010_auto_20210921_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='ApprovedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='CreatedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyversion',
            name='DeclinedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_declined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policymembers',
            name='Cover',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='Status',
            field=models.CharField(choices=[('Un-finalised', 'Un-finalised'), ('Finalised', 'Finalised'), ('Declined', 'Declined')], default='Un-finalised', max_length=20),
        ),
    ]
