# Generated by Django 3.2 on 2021-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0011_auto_20210929_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='Number',
            field=models.CharField(max_length=20),
        ),
    ]
