# Generated by Django 3.2 on 2021-05-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrates',
            old_name='Option',
            new_name='Description',
        ),
    ]
