# Generated by Django 3.2 on 2021-05-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_option_productrates_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrates',
            name='Cover',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productrates',
            name='Rate',
            field=models.FloatField(null=True),
        ),
    ]
