# Generated by Django 3.2 on 2021-05-26 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210526_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DateAdded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productrates',
            name='AgeFrom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrates',
            name='AgeTo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrates',
            name='DateAdded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='productrates',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
